# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/138/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/138/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oem/minishell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oem/minishell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/138/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/138/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oem/minishell/CMakeFiles /home/oem/minishell/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oem/minishell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parsing

# Build rule for target.
parsing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parsing
.PHONY : parsing

# fast build rule for target.
parsing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/build
.PHONY : parsing/fast

args_package.o: args_package.c.o

.PHONY : args_package.o

# target to build an object file
args_package.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/args_package.c.o
.PHONY : args_package.c.o

args_package.i: args_package.c.i

.PHONY : args_package.i

# target to preprocess a source file
args_package.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/args_package.c.i
.PHONY : args_package.c.i

args_package.s: args_package.c.s

.PHONY : args_package.s

# target to generate assembly for a file
args_package.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/args_package.c.s
.PHONY : args_package.c.s

count_string.o: count_string.c.o

.PHONY : count_string.o

# target to build an object file
count_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/count_string.c.o
.PHONY : count_string.c.o

count_string.i: count_string.c.i

.PHONY : count_string.i

# target to preprocess a source file
count_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/count_string.c.i
.PHONY : count_string.c.i

count_string.s: count_string.c.s

.PHONY : count_string.s

# target to generate assembly for a file
count_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/count_string.c.s
.PHONY : count_string.c.s

create_space_around.o: create_space_around.c.o

.PHONY : create_space_around.o

# target to build an object file
create_space_around.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/create_space_around.c.o
.PHONY : create_space_around.c.o

create_space_around.i: create_space_around.c.i

.PHONY : create_space_around.i

# target to preprocess a source file
create_space_around.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/create_space_around.c.i
.PHONY : create_space_around.c.i

create_space_around.s: create_space_around.c.s

.PHONY : create_space_around.s

# target to generate assembly for a file
create_space_around.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/create_space_around.c.s
.PHONY : create_space_around.c.s

display.o: display.c.o

.PHONY : display.o

# target to build an object file
display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/display.c.o
.PHONY : display.c.o

display.i: display.c.i

.PHONY : display.i

# target to preprocess a source file
display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/display.c.i
.PHONY : display.c.i

display.s: display.c.s

.PHONY : display.s

# target to generate assembly for a file
display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/display.c.s
.PHONY : display.c.s

free_parsing_line.o: free_parsing_line.c.o

.PHONY : free_parsing_line.o

# target to build an object file
free_parsing_line.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/free_parsing_line.c.o
.PHONY : free_parsing_line.c.o

free_parsing_line.i: free_parsing_line.c.i

.PHONY : free_parsing_line.i

# target to preprocess a source file
free_parsing_line.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/free_parsing_line.c.i
.PHONY : free_parsing_line.c.i

free_parsing_line.s: free_parsing_line.c.s

.PHONY : free_parsing_line.s

# target to generate assembly for a file
free_parsing_line.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/free_parsing_line.c.s
.PHONY : free_parsing_line.c.s

ft_strcmp.o: ft_strcmp.c.o

.PHONY : ft_strcmp.o

# target to build an object file
ft_strcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strcmp.c.o
.PHONY : ft_strcmp.c.o

ft_strcmp.i: ft_strcmp.c.i

.PHONY : ft_strcmp.i

# target to preprocess a source file
ft_strcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strcmp.c.i
.PHONY : ft_strcmp.c.i

ft_strcmp.s: ft_strcmp.c.s

.PHONY : ft_strcmp.s

# target to generate assembly for a file
ft_strcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strcmp.c.s
.PHONY : ft_strcmp.c.s

ft_strdup.o: ft_strdup.c.o

.PHONY : ft_strdup.o

# target to build an object file
ft_strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strdup.c.o
.PHONY : ft_strdup.c.o

ft_strdup.i: ft_strdup.c.i

.PHONY : ft_strdup.i

# target to preprocess a source file
ft_strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strdup.c.i
.PHONY : ft_strdup.c.i

ft_strdup.s: ft_strdup.c.s

.PHONY : ft_strdup.s

# target to generate assembly for a file
ft_strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/ft_strdup.c.s
.PHONY : ft_strdup.c.s

get_next_line.o: get_next_line.c.o

.PHONY : get_next_line.o

# target to build an object file
get_next_line.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line.c.o
.PHONY : get_next_line.c.o

get_next_line.i: get_next_line.c.i

.PHONY : get_next_line.i

# target to preprocess a source file
get_next_line.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line.c.i
.PHONY : get_next_line.c.i

get_next_line.s: get_next_line.c.s

.PHONY : get_next_line.s

# target to generate assembly for a file
get_next_line.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line.c.s
.PHONY : get_next_line.c.s

get_next_line_utils.o: get_next_line_utils.c.o

.PHONY : get_next_line_utils.o

# target to build an object file
get_next_line_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line_utils.c.o
.PHONY : get_next_line_utils.c.o

get_next_line_utils.i: get_next_line_utils.c.i

.PHONY : get_next_line_utils.i

# target to preprocess a source file
get_next_line_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line_utils.c.i
.PHONY : get_next_line_utils.c.i

get_next_line_utils.s: get_next_line_utils.c.s

.PHONY : get_next_line_utils.s

# target to generate assembly for a file
get_next_line_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/get_next_line_utils.c.s
.PHONY : get_next_line_utils.c.s

init_pipe.o: init_pipe.c.o

.PHONY : init_pipe.o

# target to build an object file
init_pipe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_pipe.c.o
.PHONY : init_pipe.c.o

init_pipe.i: init_pipe.c.i

.PHONY : init_pipe.i

# target to preprocess a source file
init_pipe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_pipe.c.i
.PHONY : init_pipe.c.i

init_pipe.s: init_pipe.c.s

.PHONY : init_pipe.s

# target to generate assembly for a file
init_pipe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_pipe.c.s
.PHONY : init_pipe.c.s

init_struct.o: init_struct.c.o

.PHONY : init_struct.o

# target to build an object file
init_struct.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_struct.c.o
.PHONY : init_struct.c.o

init_struct.i: init_struct.c.i

.PHONY : init_struct.i

# target to preprocess a source file
init_struct.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_struct.c.i
.PHONY : init_struct.c.i

init_struct.s: init_struct.c.s

.PHONY : init_struct.s

# target to generate assembly for a file
init_struct.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/init_struct.c.s
.PHONY : init_struct.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/main.c.s
.PHONY : main.c.s

new_split.o: new_split.c.o

.PHONY : new_split.o

# target to build an object file
new_split.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/new_split.c.o
.PHONY : new_split.c.o

new_split.i: new_split.c.i

.PHONY : new_split.i

# target to preprocess a source file
new_split.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/new_split.c.i
.PHONY : new_split.c.i

new_split.s: new_split.c.s

.PHONY : new_split.s

# target to generate assembly for a file
new_split.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/new_split.c.s
.PHONY : new_split.c.s

parsing.o: parsing.c.o

.PHONY : parsing.o

# target to build an object file
parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing.c.o
.PHONY : parsing.c.o

parsing.i: parsing.c.i

.PHONY : parsing.i

# target to preprocess a source file
parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing.c.i
.PHONY : parsing.c.i

parsing.s: parsing.c.s

.PHONY : parsing.s

# target to generate assembly for a file
parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing.c.s
.PHONY : parsing.c.s

parsing_pipe.o: parsing_pipe.c.o

.PHONY : parsing_pipe.o

# target to build an object file
parsing_pipe.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_pipe.c.o
.PHONY : parsing_pipe.c.o

parsing_pipe.i: parsing_pipe.c.i

.PHONY : parsing_pipe.i

# target to preprocess a source file
parsing_pipe.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_pipe.c.i
.PHONY : parsing_pipe.c.i

parsing_pipe.s: parsing_pipe.c.s

.PHONY : parsing_pipe.s

# target to generate assembly for a file
parsing_pipe.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_pipe.c.s
.PHONY : parsing_pipe.c.s

parsing_quote.o: parsing_quote.c.o

.PHONY : parsing_quote.o

# target to build an object file
parsing_quote.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_quote.c.o
.PHONY : parsing_quote.c.o

parsing_quote.i: parsing_quote.c.i

.PHONY : parsing_quote.i

# target to preprocess a source file
parsing_quote.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_quote.c.i
.PHONY : parsing_quote.c.i

parsing_quote.s: parsing_quote.c.s

.PHONY : parsing_quote.s

# target to generate assembly for a file
parsing_quote.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_quote.c.s
.PHONY : parsing_quote.c.s

parsing_redir.o: parsing_redir.c.o

.PHONY : parsing_redir.o

# target to build an object file
parsing_redir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_redir.c.o
.PHONY : parsing_redir.c.o

parsing_redir.i: parsing_redir.c.i

.PHONY : parsing_redir.i

# target to preprocess a source file
parsing_redir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_redir.c.i
.PHONY : parsing_redir.c.i

parsing_redir.s: parsing_redir.c.s

.PHONY : parsing_redir.s

# target to generate assembly for a file
parsing_redir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/parsing_redir.c.s
.PHONY : parsing_redir.c.s

several_string.o: several_string.c.o

.PHONY : several_string.o

# target to build an object file
several_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/several_string.c.o
.PHONY : several_string.c.o

several_string.i: several_string.c.i

.PHONY : several_string.i

# target to preprocess a source file
several_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/several_string.c.i
.PHONY : several_string.c.i

several_string.s: several_string.c.s

.PHONY : several_string.s

# target to generate assembly for a file
several_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parsing.dir/build.make CMakeFiles/parsing.dir/several_string.c.s
.PHONY : several_string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... parsing"
	@echo "... args_package.o"
	@echo "... args_package.i"
	@echo "... args_package.s"
	@echo "... count_string.o"
	@echo "... count_string.i"
	@echo "... count_string.s"
	@echo "... create_space_around.o"
	@echo "... create_space_around.i"
	@echo "... create_space_around.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... free_parsing_line.o"
	@echo "... free_parsing_line.i"
	@echo "... free_parsing_line.s"
	@echo "... ft_strcmp.o"
	@echo "... ft_strcmp.i"
	@echo "... ft_strcmp.s"
	@echo "... ft_strdup.o"
	@echo "... ft_strdup.i"
	@echo "... ft_strdup.s"
	@echo "... get_next_line.o"
	@echo "... get_next_line.i"
	@echo "... get_next_line.s"
	@echo "... get_next_line_utils.o"
	@echo "... get_next_line_utils.i"
	@echo "... get_next_line_utils.s"
	@echo "... init_pipe.o"
	@echo "... init_pipe.i"
	@echo "... init_pipe.s"
	@echo "... init_struct.o"
	@echo "... init_struct.i"
	@echo "... init_struct.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... new_split.o"
	@echo "... new_split.i"
	@echo "... new_split.s"
	@echo "... parsing.o"
	@echo "... parsing.i"
	@echo "... parsing.s"
	@echo "... parsing_pipe.o"
	@echo "... parsing_pipe.i"
	@echo "... parsing_pipe.s"
	@echo "... parsing_quote.o"
	@echo "... parsing_quote.i"
	@echo "... parsing_quote.s"
	@echo "... parsing_redir.o"
	@echo "... parsing_redir.i"
	@echo "... parsing_redir.s"
	@echo "... several_string.o"
	@echo "... several_string.i"
	@echo "... several_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

